---
brand: Heat KPI Dashboard
graphite: http://graphite.rs-heat.com
secret_key: secret_test_key
debug: true
regions:
  - dfw
  - ord
  - iad
  - lon
  - syd
  - hkg
default_span: -7days
metrics:
  - display_name: Uptime
    type: uptime
    unit: percent
    null_zero: false
    targets:
      - 'stats.timers.uptime.{region}.mean'
  - display_name: Percent Requests Per Minute (90 Percentile) 
    type: average
    unit: minutes
    null_zero: true
    targets:
      - 'removeAbovePercentile(sumSeries(hitcount(stats.heat.*_{region}_rs-heat_com.api.response_*.requests,"1min")),90)'
  - display_name: Percent 50x Responses
    type: percent
    unit: percent
    null_zero: true
    targets:
      - 'removeAbovePercentile(sumSeries(hitcount(stats.heat.*_{region}_rs-heat_com.api.response_5*.requests, "30s")),90)'
      - 'removeAbovePercentile(sumSeries(hitcount(stats.heat.*_{region}_rs-heat_com.api.response_2*.requests, "30s"),hitcount(stats.heat.*_{region}_rs-heat_com.api.response_3*.requests, "30s"),hitcount(stats.heat.*_{region}_rs-heat_com.api.response_4*.requests, "30s")),90)'
  - display_name: Overall Average API Response Time
    type: average
    unit: seconds
    null_zero: false
    targets:
      - 'removeAbovePercentile(averageSeries(stats.timers.heat.*_{region}_rs-heat_com.api.response_*.response_time.mean),90)'
  - display_name: List Stacks Response Time
    type: average
    unit: seconds
    null_zero: false
    targets:
      - 'removeAbovePercentile(averageSeries(stats.timers.heat.*_{region}_rs-heat_com.api.actions.list_stacks.mean),90)'
  - display_name: List Resources Response Time
    type: average
    unit: seconds
    null_zero: false
    targets:
      - 'removeAbovePercentile(averageSeries(stats.timers.heat.*_{region}_rs-heat_com.api.actions.list_resources.mean),90)'
  - display_name: Get Stack Response Time
    type: average
    unit: seconds
    null_zero: false
    targets:
      - 'removeAbovePercentile(averageSeries(stats.timers.heat.*_{region}_rs-heat_com.api.actions.get_stack.mean),90)'
  - display_name: Create Stack Response Time
    type: average
    unit: seconds
    null_zero: false
    targets:
      - 'removeAbovePercentile(averageSeries(stats.timers.heat.*_{region}_rs-heat_com.api.actions.create_stack.mean),90)'
  - display_name: Preview Stack Response Time
    type: average
    unit: seconds
    null_zero: false
    targets:
      - 'removeAbovePercentile(averageSeries(stats.timers.heat.*_{region}_rs-heat_com.api.actions.preview_stack.mean),90)'
  - display_name: Delete Stack Response Time
    type: average
    unit: seconds
    null_zero: false
    targets:
      - 'removeAbovePercentile(averageSeries(stats.timers.heat.*_{region}_rs-heat_com.api.actions.delete_stack.upper_90),90)'
  - display_name: Requests Per Minute
    type: average
    unit: minutes
    null_zero: true
    targets:
      - 'sumSeries(hitcount(stats.heat.*_{region}_rs-heat_com.api.response_*.requests,"1min"))'
